
# POSTGRES BEGIN #

INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('cars_per_page', '30');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('year_start', '1980');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('year_end', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_submit_make', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_submit_model', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('dateformat', 'd M Y H:i');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('version', '2.0.B3-DEV');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('default_make_id', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('default_model_id', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('integrate_memberlist', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('integrate_viewtopic', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('integrate_profile', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('profile_thumbs', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_pm_pending_notify', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_email_pending_notify', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_pm_pending_notify_optout', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_email_pending_notify_optout', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_vehicle_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_index_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_browse_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_search_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_insurance_review_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_garage_review_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_shop_review_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_lap_menu', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_garage_header', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_header', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_header', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_latest_vehicle_index', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('latest_vehicle_index_limit', '10');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_featured_vehicle', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('index_columns', '2');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_index_columns', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('featured_vehicle_id', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('featured_vehicle_random', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('featured_vehicle_from_block', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('featured_vehicle_description', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_newest_vehicle', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('newest_vehicle_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_updated_vehicle', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('updated_vehicle_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_newest_modification', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('newest_modification_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_updated_modification', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('updated_modification_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_most_modified', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('most_modified_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_most_spent', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('most_spent_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_most_viewed', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('most_viewed_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_last_commented', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('last_commented_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_top_dynorun', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('top_dynorun_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_top_quartermile', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('top_quartermile_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_top_rating', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('top_rating_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_top_lap', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('top_lap_limit', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_vehicle_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_modification_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_lap_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_uploaded_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_remote_images', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('remote_timeout', '60');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_mod_gallery', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_gallery', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_gallery', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_lap_gallery', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('gallery_limit', '10');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('max_image_kbytes', '1024');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('max_image_resolution', '1024');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('thumbnail_resolution', '150');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_watermark', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('watermark_type', 'non_permanent');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('watermark_source', 'watermark.png');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_quartermile_image_required', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('quartermile_image_required_limit', '13');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_dynorun_image_required', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('dynorun_image_required_limit', '300');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_tracktime', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_add_track', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_track_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_lap_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_insurance', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_insurance_search', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_submit_business', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_business_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('rating_permanent', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('rating_always_updateable', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('minimum_ratings_required', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_guestbooks', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_guestbooks_bbcode', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_guestbooks_comment_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_user_submit_product', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_product_approval', '0');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_product_search', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_service', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_blogs', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('enable_blogs_bbcode', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('default_vehicle_quota', '1');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('default_upload_quota', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('default_remote_quota', '5');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('add_groups', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('add_groups_quotas', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('upload_groups', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('upload_groups_quotas', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('remote_groups', '');
INSERT INTO phpbb_garage_config (config_name, config_value) VALUES ('remote_groups_quotas', '');

INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_img_attached', 'garage_camera.gif', '', 20, 20, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_img_attached', 'garage_camera.gif', '', 20, 20, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_toggle', 'garage_toggle.gif', '' , 18, 18, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_edit', 'garage_edit.gif', '' , 20, 20, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_edit', 'garage_edit.gif', '', 20, 20, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_delete', 'garage_delete.gif', '', 20, 20, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_delete', 'garage_delete.gif', '' , 20, 20, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_icon_garage', 'icon_miniprofile_garage.gif', '', 20, 20, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_icon_garage', 'icon_garage.gif', 'en', 20, 72, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_main_menu', 'garage_main_menu.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_browse', 'garage_browse.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_search', 'garage_search.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_quartermile_table', 'garage_quartermile_table.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_lap_table', 'garage_lap_table.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_dynorun_table', 'garage_dynorun_table.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_garage_review', 'garage_garage_review.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_shop_review', 'garage_shop_review.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_insurance_review', 'garage_insurance_review.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_create_vehicle', 'garage_new_vehicle.gif', 'en', 50, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_create_vehicle', 'garage_create_vehicle.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_edit_vehicle', 'garage_edit_vehicle.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_edit_vehicle', 'garage_edit_vehicle.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_delete_vehicle', 'garage_delete_vehicle.gif', 'en', 25, 135, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_delete_vehicle', 'garage_delete_vehicle.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_view_vehicle', 'garage_view_vehicle.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_view_vehicle', 'garage_view_vehicle.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_modification', 'garage_new_modification.gif', 'en', 25, 135, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_modification', 'garage_add_modification.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_insurance', 'garage_new_premium.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_insurance', 'garage_add_insurance.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_dynorun', 'garage_new_dynorun.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_dynorun', 'garage_add_dynorun.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_quartermile', 'garage_new_quartermile.gif', 'en', 25, 135, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_quartermile', 'garage_add_quartermile.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_lap', 'garage_new_lap.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_lap', 'garage_add_lap.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_service', 'garage_new_service.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_add_service', 'garage_add_service.gif', 'en', 33, 130, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_main_vehicle', 'garage_main_vehicle.gif', 'en', 25, 120, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_main_vehicle', 'garage_main_vehicle.gif', 'en', 130, 33, 2);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_no_thumb', 'garage_no_thumb.gif', 'en', 25, 96, 1);
INSERT INTO phpbb_styles_imageset_data (image_name, image_filename, image_lang, image_height, image_width, imageset_id) VALUES ('garage_no_thumb', 'garage_no_thumb.gif', 'en', 33, 130, 2);

# POSTGRES COMMIT #
